application: truthfinder
version: 1
runtime: python
api_version: 1

handlers:
- url: /media
  static_dir: media

- url: /admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: /.*
  script: main.py
